### ISSUE TITLE
Disabling inline code on a trailing cursor doesn't allow to re-apply it

### ISSUE THREAD

**Issue by aringenbach** [matrix-org/matrix-rich-text-editor#527] opened 2023-01-26 14:29 UTC
```rust
let mut model = cm("text|");
model.inline_code();
model.replace_text("text");
model.inline_code();
model.inline_code();
model.replace_text("text");
assert_eq!(tx(&model), "text<code>text</code>text|");
```

Found issue while fixing #495 
It seems that when `inlineCode` is added to `toggled_format_types` in order to disable it on next input it cannot properly be removed again. Hitting the button twice should have re-enabled the inline code and further text should have been inside the `<code>`.

Note: other "format" like e.g. bold work fine for this use case.

**Comment by alunturner** [comment] 2023-06-05 15:07
Tested on 5 Jun and that test now passes on `main`. @aringenbach I'm going to close this issue - if I'm missing something and the problem is still relevant somehow then please feel free to reopen.

**Closed by alunturner** 2023-06-05 15:07 UTC
Labels: bug, A-Rich-Text-Editor
