### ISSUE TITLE
"deleteWordBackward" and "deleteWordForward" not supported

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-rich-text-editor#397] opened 2022-12-13 15:55 UTC
Type/enter "ctrl del" -> Console message: "Unknown input type: deleteWordBackward".

**Comment by menturion** [comment] 2022-12-14 10:26
### Addendum ###

Same with `deleteWordForward`:  "Unknown input type: deleteWordForward".

**Comment by florianduros** [comment] 2022-12-14 18:05
The `deleteWordBackward` and `deleteWordForward` is currently under development, it should be available soon.

**Comment by florianduros** [comment] 2022-12-14 18:09
Duplicate of https://github.com/matrix-org/matrix-rich-text-editor/issues/321

**Closed by florianduros** 2022-12-14 18:09 UTC
